# Generated by Django 3.1.3 on 2020-12-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('page', models.CharField(max_length=200, verbose_name='Page')),
                ('product', models.ManyToManyField(related_name='shop', related_query_name='shop', to='products.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
    ]
